#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo "Checking Node.js..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node --version)
echo -e "Node.js version: ${GREEN}$NODE_VERSION${NC}"

echo "Checking npm..."
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."
npm run build

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running tests..."
npm test

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: coding-plan-assistant"
echo "Type: Node.js CLI"
echo "Tests: $(npm test 2>&1 | tail -1)"
echo ""
